name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and publish Docker Image to GitHub Packages Registry
      uses: VaultVulp/gp-docker-action@1.1.2
      with:
        # GitHub token to push Docker image to GitHub Packages
        github-token: ${{ secrets.GITHUB_TOKEN }}
        # Docker Image name
        image-name: dotenv2dockerfile
        # Docker Image tag
        extract-git-tag: true
